### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by LucioC** [dong-x16/PortraitNet#9]
Hello,

You seem to have a good work here, could you please add a license to the code you are distributing? 
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository
"You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project."

Thanks

**Comment by InternetMaster1** [comment]
Yes please. Is this project open source?
